// src/lib/rolls.ts
import type { AlbumMeta } from "./types";

export const albums: AlbumMeta[] = [
  {
    i: 1,
    date: 202306,
    film: { iso: 100, stock: "Ektar" },
    slug: "tustin",
    title: "Tustin",
    location: [],
    page: true,
  },
  {
    i: 2,
    date: 202306,
    film: { iso: 100, stock: "Ektar" },
    slug: "joshua_1",
    title: "Joshua Tree no. 1",
    location: [],
    page: true,
  },
  {
    i: 3,
    date: 202307,
    film: { iso: 200, stock: "Gold" },
    slug: "bemidji",
    title: "Bemidji",
    location: [],
    page: true,
  },
  {
    i: 4,
    date: 202307,
    film: null,
    slug: "carlsbad",
    title: "Carlsbad",
    location: [],
    page: true,
  },
  {
    i: 6,
    date: 202308,
    film: { iso: 800, stock: "Cinestill" },
    slug: "arrowhead",
    title: "Arrowhead",
    location: [],
    page: true,
  },
  {
    i: 7,
    date: 202308,
    film: { iso: 160, stock: "Portra" },
    slug: "yosemite",
    title: "Yosemite",
    location: [],
    page: true,
  },
  {
    i: 8,
    date: 202401,
    film: null,
    slug: "joshua_2",
    title: "Joshua Tree no. 2",
    location: [],
    page: false,
  },
  {
    i: 9,
    date: 202403,
    film: { iso: 400, stock: "Fujifilm" },
    slug: "sequoia",
    title: "Sequoia",
    location: [],
    page: true,
  },
  {
    i: 10,
    date: 202406,
    film: { iso: 100, stock: "Ektachrome" },
    slug: "zion",
    title: "Zion",
    location: [],
    page: true,
  },
  {
    i: 12,
    date: 202505,
    film: { iso: 100, stock: "Ektar" },
    slug: "yellowstone",
    title: "Yellowstone",
    location: [],
    page: true,
  },
  {
    i: 13,
    date: 202505,
    film: { iso: 100, stock: "Ektachrome" },
    slug: "redwoods",
    title: "Redwoods",
    location: [],
    page: true,
  },
  {
    i: 14,
    date: 202512,
    film: null,
    slug: "hawaii",
    title: "Hawaii",
    location: [],
    page: true,
  },
  {
    i: 15,
    date: 202601,
    film: { iso: 200, stock: "Kodacolor" },
    slug: "death",
    title: "Death Valley",
    location: ["Death Valley National Park"],
    page: true,
  },
  {
    i: 16,
    date: 202603,
    film: { iso: 160, stock: "Portra" },
    slug: "pinnacles",
    title: "Pinnacles",
    location: ["Pinnacles National Park", "Big Sur", "San Clemente"],
    page: true,
  },
  {
    i: 17,
    date: 202605,
    film: { iso: 200, stock: "Kodacolor" },
    slug: "utah",
    title: "Utah",
    location: [],
    page: true,
  },
  {
    i: 18,
    date: 202606,
    film: { iso: 400, stock: "Portra" },
    slug: "jmt",
    title: "John Muir Trail",
    location: [],
    page: true,
  },
];

export const albumSlugs = albums.map((a) => ({ slug: a.slug }));
export const getAlbumMeta = (slug: string) =>
  albums.find((a) => a.slug === slug);
