// src/lib/albums.ts
import type { AlbumMeta } from "./types";

export const albums: AlbumMeta[] = [
  {
    i: 1,
    date: 202306,
    film: { iso: 100, stock: "Ektar" },
    slug: "tustin",
    title: "Tustin",
    page: true,
  },
  {
    i: 2,
    date: 202306,
    film: { iso: 100, stock: "Ektar" },
    slug: "joshua_1",
    title: "Joshua Tree no. 1",
    page: true,
  },
  {
    i: 3,
    date: 202307,
    film: { iso: 200, stock: "Gold" },
    slug: "bemidji",
    title: "Bemidji",
    page: true,
  },
  {
    i: 4,
    date: 202307,
    film: { iso: 401, stock: "Pan" },
    slug: "sandigo",
    title: "San Diego",
    page: true,
  },
  // {
  //   i: 5,
  //   date: 202307,
  //   film: { iso: 400, stock: "UltraMax" },
  //   slug: "sbarbara",
  //   title: "Santa Barbara",
  // },
  {
    i: 6,
    date: 202308,
    film: { iso: 800, stock: "Cinestill" },
    slug: "arrowhead",
    title: "Arrowhead",
    page: true,
  },
  {
    i: 7,
    date: 202308,
    film: { iso: 160, stock: "Portra" },
    slug: "yosemite",
    title: "Yosemite",
    page: true,
  },
  {
    i: 8,
    date: 202401,
    film: { iso: 401, stock: "???" },
    slug: "joshua_2",
    title: "Joshua Tree no. 2",
    page: false,
  },
  {
    i: 9,
    date: 202403,
    film: { iso: 400, stock: "Fujifilm" },
    slug: "sequoia",
    title: "Sequoia",
    page: true,
  },
  {
    i: 10,
    date: 202406,
    film: { iso: 100, stock: "Ektachrome" },
    slug: "zion",
    title: "Zion",
    page: true,
  },
  // {
  //   i: 11,
  //   date: 202410,
  //   film: { iso: 200, stock: "Gold" },
  //   slug: "yale",
  //   title: "Yale",
  // },
  {
    i: 12,
    date: 202505,
    film: { iso: 100, stock: "Ektar" },
    slug: "teton",
    title: "Yellowstone",
    page: true,
  },
  {
    i: 13,
    date: 202505,
    film: { iso: 100, stock: "Ektachrome" },
    slug: "redwoods",
    title: "Redwoods",
    page: true,
  },
  {
    i: 14,
    date: 202512,
    film: { iso: 400, stock: "???" },
    slug: "hawaii",
    title: "Hawaii",
    page: true,
  },
  {
    i: 15,
    date: 202601,
    film: { iso: 200, stock: "Kodak" },
    slug: "death",
    title: "Death Valley",
    page: true,
  },
];

export const albumSlugs = albums.map((a) => ({ slug: a.slug }));
export const getAlbumMeta = (slug: string) =>
  albums.find((a) => a.slug === slug);
